Repository rest-for-physics/framework, pull requests merged in 2023-09, with the labels that each got.

#473 RML metadata instances will allow now env variables in the name definition.
  source/framework/core/src/TRestMetadata.cxx
Labels: enhancement, development

#460 Increasing default verbose level of `restManager` to `Info`
  source/bin/restManager.cxx
  source/framework/core/src/TRestDataSet.cxx
Labels: enhancement

#475 Remove PandaX from validation pipeline
  .github/workflows/validation.yml
  pipeline/panda-x/CoBo_AsAd0_2019-03-15.graw
  pipeline/panda-x/P3AutoChain.rml
  pipeline/pandaxiii_MC/AllProcesses.rml
  pipeline/pandaxiii_MC/README.md
  pipeline/pandaxiii_MC/Xe136bb0n_small_reference.root
  pipeline/pandaxiii_MC/Xe136bb0n_validation.root
  pipeline/pandaxiii_MC/Xe136bb0n_validation_G4_v10.4.3.root
  pipeline/pandaxiii_MC/Xe136bb0n_validation_root6.20.root
  pipeline/pandaxiii_MC/plots.rml
  pipeline/pandaxiii_MC/processes_2D.rml
  pipeline/pandaxiii_MC/readout-140kg.rml
  pipeline/pandaxiii_MC/readouts.rml
  pipeline/pandaxiii_data/P3AutoChain.rml
  pipeline/pandaxiii_data/validation.root
Labels: policy
