Repository rest-for-physics/framework, pull requests merged in 2023-06, with the labels that each got.

#431 REST_StringHelper::isAExpression. Fixing a bug
  source/framework/tools/src/TRestStringHelper.cxx
Labels: bug

#433 Updating validation.yml for using new readout validation
  .github/workflows/validation.yml
  examples/01.alphaTrack/readout/readouts.root
  pipeline/trex/run.xml
Labels: development

#450 Add macro to find library version from git
  cmake/LibraryVersion.cmake
  source/CMakeLists.txt
Labels: cmake

#441 Updating restRoot behaviour
  cmake/thisREST.cmake
  macros/REST_OpenInputFile.C
  source/bin/restRoot.cxx
  source/framework/core/src/TRestAnalysisPlot.cxx
  source/framework/core/src/TRestMetadata.cxx
  source/framework/core/src/TRestMetadataPlot.cxx
  source/framework/core/src/TRestRun.cxx
  source/framework/tools/inc/TRestReflector.h
  source/framework/tools/inc/TRestTools.h
  source/framework/tools/src/TRestTools.cxx
Labels: enhancement
